#! /bin/sh

## autostarting
$HOME/.config/polybar/launch.sh &
xrdb -merge ~/.Xresources &
compton --config ~/.config/picom/picom.conf &
light-locker &
nm-applet &
xsetroot -cursor_name left_ptr &
xss-lock -- i3lock &
xfce4-power-manager --daemon &
nitrogen --restore &
xfsettingsd --daemon &
cat ~/.cache/wal/sequences &
sxhkd &
emacs --daemon &

# switch caps and esc key
setxkbmap -option "caps:swapescape" &

# MPD daemon start (if no other user instance exists)
[ ! -s ~/.config/mpd/pid ] && mpd &

# source the colors.
#. "${HOME}/.cache/wal/colors.sh"


# Tiling Scheme
#bspc config longest_side

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc monitor -d code web vedio files gfx extra extra

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config ignore_ewmh_struts   false
bspc config ignore_ewmh_focus    false

# Window Rules
bspc rule -a kitty state = floating 
bspc rule -a Xdg-desktop-portal-gtk state = floating
bspc rule -a Lightdm-gtk-greeter-settings state = floating
bspc rule -a Pavucontrol state = floating 
bspc rule -a Brave state = floating
bspc rule -a Gcolor3 state = floating
bspc rule -a Emacs desktop='^1' state = tiled focus=on follow=on
bspc rule -a Eclipse desktop='^1' state = floating focus=on follow=on
bspc rule -a Brave-browser desktop='^2' state = tiled focus=on follow=on
bspc rule -a mpv desktop='^3' state = fullscreen focus=on follow=on
bspc rule -a Org.gnome.Nautilus desktop='^4' focus=on follow=on
bspc rule -a Zathura desktop='^4' state=tiled focus=on follow=on
bspc rule -a libreoffice-impress desktop='^4' state = pseudo_tiled focus=on follow=on
bspc rule -a Virt-manager desktop='^5' state=floating focus=on follow=on
bspc rule -a Gimp-2.10 desktop='^5' state = floating focus=on follow=on
bspc rule -a Olive desktop='^5' state = floating focus=on follow=on
