#! /bin/sh

### autostarting
$HOME/.config/polybar/launch.sh &
compton &
xsetroot -cursor_name left_ptr &
sxhkd &
nitrogen --restore &
# source the colors.
. "${HOME}/.cache/wal/colors.sh"


# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc monitor -d code web terminal music vedio files games

bspc config border_width         4
bspc config window_gap           12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true


# Window Rules
bspc rule -a Alacritty state = floating 
bspc rule -a Emacs desktop='^1' state = tiled
bspc rule -a Eclipse desktop='^1' state = floating
bspc rule -a Tilix desktop='^3' state = pseudo_tiled
bspc rule -a Lollypop desktop='^4' state = pseudo_tiled
bspc rule -a mpv desktop='^5' state = fullscreen
bspc rule -a Org.gnome.Nautilus desktop='^6'
bspc rule -a libreoffice-impress desktop='^6' state = pseudo_tiled
bspc rule -a Lutris desktop='^7' state = floating
