--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ishan/Wallpapers/art/ultragigacity"

-- Special
background="#120d0d"
foreground="#e8d78e"
cursor="#e8d78e"

-- Colors
color0="#120d0d"
color1="#684525"
color2="#70472C"
color3="#523C50"
color4="#985D27"
color5="#BC6429"
color6="#DF9C1B"
color7="#e8d78e"
color8="#a29663"
color9="#684525"
color10="#70472C"
color11="#523C50"
color12="#985D27"
color13="#BC6429"
color14="#DF9C1B"
color15="#e8d78e"
