# Shell variables
# Generated by 'wal'
wallpaper='/home/ishan/Wallpapers/art/ultragigacity'

# Special
background='#120d0d'
foreground='#e8d78e'
cursor='#e8d78e'

# Colors
color0='#120d0d'
color1='#684525'
color2='#70472C'
color3='#523C50'
color4='#985D27'
color5='#BC6429'
color6='#DF9C1B'
color7='#e8d78e'
color8='#a29663'
color9='#684525'
color10='#70472C'
color11='#523C50'
color12='#985D27'
color13='#BC6429'
color14='#DF9C1B'
color15='#e8d78e'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
