--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#1f2022"
foreground="#a3a3a3"
cursor="#a3a3a3"

-- Colors
color0="#1f2022"
color1="#f2241f"
color2="#67b11d"
color3="#b1951d"
color4="#4f97d7"
color5="#a31db1"
color6="#2d9574"
color7="#a3a3a3"
color8="#585858"
color9="#f2241f"
color10="#67b11d"
color11="#b1951d"
color12="#4f97d7"
color13="#a31db1"
color14="#2d9574"
color15="#f8f8f8"
